# .streamlit/secrets.toml
[motherduck]
token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdWwuYm95Y2VAcG0ubWUiLCJzZXNzaW9uIjoicGF1bC5ib3ljZS5wbS5tZSIsInBhdCI6InQ0WjRhNlNNQUVjblAyNEZvcFR5RTZ0X05BNkRpdFY5YU1lZWExenpULVUiLCJ1c2VySWQiOiI4MmIxZTQ1Ny0xZjA0LTQ2YWQtODcyZS1mODdlZTViNGMwYjAiLCJpc3MiOiJtZF9wYXQiLCJyZWFkT25seSI6ZmFsc2UsInRva2VuVHlwZSI6InJlYWRfd3JpdGUiLCJpYXQiOjE3NTAzNTA5Mzl9.CbKV606TOn7evoKErfl1ATFnejwVaIJAw2E1RBGk3v8'
